### ISSUE TITLE
Make a compraison of front-end technologies for a multi-lingual blogging website

### ISSUE THREAD

**Issue by fsheikh** [fsheikh/sample_code#1]
Document pros and cons of React and Angular front-end technologies under the wiki: https://github.com/fsheikh/sample_code/wiki/Deurdu:-A-multilingual-blogging-website

**Comment by MuhammadTaha01** [comment]
### React:

**Pros:-**
- Supports single age application
- Component based architecture
- Easy to be adopted for beginners
- Highly scalable
- Huge developer support
- Supports internationalization framework like i18next

**Cons:-**
- Requires additional libraries for routing and state-management ( redux etc.. )

### Angular:

**Pros:-**
-  Supports single age application ( same as react )
- Component based architecture ( same as react )
- Easy to be adopted for beginners ( same as react )
- Highly scalable ( same as react )
- Huge developer support ( same as react )
- Supports internationalization framework like i18next ( same as react )
- Good for large scale applications

**Cons:-**
- Not a huge developer support as compare to react
- Might be difficult for beginners as it has some of the resemblance with TypeScript

**Conclusion:**
Both React and Angular are front-end technologies and both works on server and client side. 
Both supports component based architecture. Both supports i18next framework which we are going to be needed in-case of adding "Internationalization" feature in our website.
The only major thing which differs React from Angular is developer's support. 
Else are minor thing's, they will not disturbed the working and data-flow time of our website.

**Comment by fsheikh** [comment]
Please format the pro and cons as a [table](https://gist.github.com/ww9/44f08d44327a40d2ab309a349bebec57#tables) and put them in the appropriate wiki [section](https://github.com/fsheikh/sample_code/wiki/Deurdu:-A-multilingual-blogging-website#comparison-of-front-end-technologies)

**Comment by MuhammadTaha01** [comment]
## Comparison of React and Angular

| Feature                                      | React                                                | Angular                                      |
|-----------------------------------|------------------------------------------------------|----------------------------------------------|
| Supports Single Page Applications            | Yes                                                  | Yes                                          |
| Component-based Architecture                 | Yes                                                  | Yes                                          |
| Easy to be Adopted for Beginners             | Yes                                                  | Yes                                          |
| Highly Scalable                              | Yes                                                  | Yes                                          |
| Huge Developer Support                       | Yes                                                  | No                                           |
| Supports Internationalization Frameworks     | Yes (e.g., i18next)                                  | Yes (e.g., i18next)                          |
| Good for Large Scale Applications            | No                                                   | Yes                                          |
| Requires Additional Libraries for Routing and State Management | Yes (e.g., Redux, React Router)                      | No (built-in solutions available)            |
| Might be Difficult for Beginners             | No                                                   | Yes (due to TypeScript)                      |

### Conclusion

Both React and Angular are front-end technologies that support single-page applications and component-based architectures. Both also support internationalization frameworks like i18next, which is necessary for adding the "Internationalization" feature to our website.

The primary difference between React and Angular is the level of developer support. React has a larger community and more support. Other differences, such as requiring additional libraries for routing and state management in React or the complexity of Angular for beginners due to TypeScript, are relatively minor and should not significantly impact the working and data flow of our website.

**Comment by fsheikh** [comment]
Analysis completed
