### ISSUE TITLE
Comparison of various content-management systems for a multilingual blogging site

### ISSUE THREAD

**Issue by fsheikh** [fsheikh/sample_code#2]
Document a comparison of a least three content management systems as backend for a multilingual blogging website under: https://github.com/fsheikh/sample_code/wiki/Deurdu:-A-multilingual-blogging-website. Two system that should be looked at are:

- Word-press
- Drupal

**Comment by MuhammadTaha01** [comment]
# CMS Comparison: WordPress vs. Drupal

This document provides a comparison between two popular Content Management Systems (CMS): WordPress and Drupal.

| Feature                     | WordPress                              | Drupal                              |
|-----------------------------|----------------------------------------|-------------------------------------|
| **User Friendly**           | Yes                                    | Yes                                 |
| **Ease of Use**             | Easy                                   | Difficult, requires some coding knowledge |
| **Beginner Friendly**       | Yes                                    | No, requires some coding skills     |
| **Available Plugins**       | 55,000+                                | 44,000+                             |
| **CMS Market Share**        | 69.5% (as per Google stats)            | 2.3% (as per Google stats)          |
| **One-Click Availability**  | Yes                                    | Yes                                 |
| **Free Themes**             | 6800+                                  | 2800+                               |
|**Security**                     | No (not a good choice for large websites)             | Yes (good choice for large websites)               |
## Conclusion

Both WordPress and Drupal are robust CMS platforms, each with its strengths and ideal use cases. WordPress stands out for its user-friendliness and extensive plugin ecosystem, making it a great choice for beginners and small to medium-sized websites. Drupal, on the other hand, offers more flexibility and power, suitable for larger, more complex sites but requires more technical expertise.

**Comment by MuhammadTaha01** [comment]
I have studied about these 2 major CMS Systems (Wordpress and Drupal) on google, and I have found out that there is much more helping material of **Wordpress** on Google, Youtube and other platforms as compare to Drupal. Also we are making the blogging website, so therefore I think that Wordpress will be a good choice for it.

What's your opinion on it?

**Comment by fsheikh** [comment]
> What's your opinion on it?

I used wordpress some years ago and found it not very programmer friendly. May be that has changed meanwhile, but lets please include Node JS in the comparison above.

**Comment by MuhammadTaha01** [comment]
# Comparison: Node.js vs. WordPress

This document provides a comparison between using Node.js and WordPress as backends for a blogging website.

| Feature                     | Node.js                                | WordPress                           |
|-----------------------------|----------------------------------------|-------------------------------------|
| **User Friendly**           | No, requires coding knowledge          | Yes                                 |
| **Ease of Use**             | Moderate, requires JavaScript/Node.js skills | Easy, minimal coding required       |
| **Beginner Friendly**       | No, better for experienced developers  | Yes, ideal for beginners            |
| **Available Plugins**       | Thousands via npm                      | 58,000+                             |
| **Community Support**       | Strong, active JavaScript community    | Extensive WordPress community       |
| **Customization**           | Highly customizable, full control over backend | Customizable with plugins and themes|
| **Scalability**             | High, handles real-time data well      | Moderate, may need optimization for high traffic |
| **Security**                | High, but depends on developer's implementation | Good, but needs regular updates and security measures |
| **Performance**             | High, non-blocking, event-driven       | Moderate, may need caching and optimization |
| **Database Flexibility**    | Works well with both SQL and NoSQL databases | Primarily uses MySQL                |
| **Multilingual Support**    | Requires implementation with libraries like i18n | Built-in support with plugins       |
| **Real-Time Capabilities**  | Excellent for real-time applications   | Limited, mainly static content      |
| **Hosting Options**         | Flexible, can be hosted anywhere       | Typically hosted on WordPress-specific hosts |

## Conclusion

### Is Node.js a Good Choice for a Blogging Website?

Node.js can be a good choice for a blogging website as we will be needing high performance, scalability, and real-time capabilities. It offers flexibility in terms of customization and database options. However, it requires a higher level of technical expertise compared to WordPress.

**Comment by fsheikh** [comment]
sounds good. Lets stick with `Node js` then at least to start with

**Comment by MuhammadTaha01** [comment]
Aoa Faheem Bhai, 
As you said in the mail earlier, to use Sqlite database, I have searched and studied about it, also the people on Youtube and google etc.. have used Sqlite for smaller projects. It's also said on their website (https://www.sqlite.org/whentouse.html) you may check it.

But however, i have made a tabular comparison of both databases. So that the picture will be clear for us, that which will be good for our blogging website.

**Comparison of mySQL or SQLITE : Which database will be better for blogging website?**

| Feature                | MySQL                                   | SQLite                                 |
|------------------------|-----------------------------------------|----------------------------------------|
| **Type**               | Server-based RDBMS                      | Server less, embedded RDBMS             |
| **Setup Complexity**   | High                                     | Low                                    |
| **Scalability**        | High                                     | Limited                                |
| **Multi-User Support** | Excellent                                | Limited                                |
| **Concurrency**        | Handles high concurrency well           | Limited concurrent writes              |
| **Performance**        | Good for large-scale applications       | Excellent for small to medium datasets |
| **Security**           | Robust security features                | Basic security features                |
| **Replication**        | Supports master-slave replication       | Not available                          |
| **ACID Compliance**    | Yes                                      | Yes                                    |
| **Resource Usage**     | Resource intensive                      | Lightweight                            |
| **Portability**        | Server-dependent                        | Highly portable (single file)          |
| **Maintenance**        | Requires regular maintenance            | Minimal maintenance required           |
| **Community Support**  | Extensive                                | Good                                   |

### Conclusion
mySQL will be a good choice as our blogging website is not a small project, it's a full stack project and for full stack project,  mySQL is a good choice. If our blogging website expects high traffic, multiple concurrent users, and requires robust security and scalability features. MySQL will handle the demands of a growing user base and the need for complex queries.

This was my side of perspective, I would also like to know your opinion too.

**Comment by fsheikh** [comment]
We can always scale up if needed, lets start with `SQLite`
